# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Build stage
FROM golang:1.25-alpine AS builder
WORKDIR /app

# Install build prerequisites
RUN apk add --no-cache ca-certificates build-base

# Copy source
COPY . .

# Build with vendored deps and static binary
ARG TARGETOS
ARG TARGETARCH
ENV CGO_ENABLED=0 \
    GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH}
RUN go env -w GOTOOLCHAIN=local \
 && go mod vendor \
 && go build -trimpath -ldflags "-s -w" -mod=vendor -o /app/mcp-victoriametrics ./cmd/mcp-victoriametrics

# Runtime stage
FROM alpine:latest
WORKDIR /app

# Install ca-certificates for HTTPS
RUN apk add --no-cache ca-certificates

# Copy binary from builder
COPY --from=builder /app/mcp-victoriametrics /usr/local/bin/mcp-victoriametrics

# Default entrypoint
ENTRYPOINT ["mcp-victoriametrics"]
